scores1={"第一名":"万嘉琦","第二名":"吴渊"}
scores2=dict(第一名="万嘉琦",第二名="吴渊")
scores3=scores2["第三名"]="万渊"
print(scores1.keys())#显示字典的keys
print(type(scores1.keys()))
keys=scores1.keys()
print(keys)
print(type(keys))
b=scores2.values()#显示字典的values
print(b)
print(type(b))
print(scores2.values())
print(type(scores2.values()))
items=scores2.items()#显示字典的items
print(items)
print(scores2)
print(scores3)
print(list(items))